### PR TITLE
Fix demo link

### PR DESCRIPTION
**Pull request by rupl**
I was perusing the docs and found a broken link. All patched up!

### CODE REVIEW

**Comment by PitPik** [comment]
Hi @rupl ,
thanks for this finding.
Well, this was a miss spelling of the folder on my server. I had javascript_implementation instead of javaScript_implementation (the capital S...).
Thanks again and Cheers,
Peter

**Comment by GildoMat** [comment]
Hi! Nice job, I'm tying to understand how is usable but the documentation it is a little bit poor. I have some troubles, in first I'm not able to use it on DIV, second, I'm not able to understand how is possible see only the bacground color and not the value string on it! May be I'm not so smart like I believe, but I haven't found this info.
Thanks for any answer.

**Comment by PitPik** [comment]
Hi @GildoMat ,
Thanks for your comment. Unfortunately I wrote a really bad implementation for the color picker. The javascript and the jQuery implementations are a bit crappy as I actually never wanted to write them in the first place. It was supposed to be a color tool with a UI and the fact that every programmer needs to implement it differently anyhow, I first passed on writing an implementation at all.
The fact though that most people just want to use it without putting any additional afford into it made me then write a quite simple implementation... well, this obviously doesn't make most people really happy anyhow (because it's crappy ;o) I tried to demonstrate on my demo-page how easy it would be to even write different color pickers (RGB, HSL bars, the circle, etc...) and include the existing UI to it...
Well, I now see that most people don't have time to program them selfs. They want to use ready to go and out of the box things.
How would you suggest that I could people participate and write some nice implementations? I barely have time to do that as my focus is on other things these days...
Any suggestions?

Cheers,
Peter

**Comment by PitPik** [comment]
Hi @GildoMat again,
BTW, if you need to have a DIV only and no text in it and you're fine with a simpler color picker you might want to try [https://github.com/PitPik/tinyColorPicker](tinyColorPicker). It's way smaller and has a better implementation (although I will work on it as well in the future, as it also has some flaws... but way less though ;o)

**Comment by GildoMat** [comment]
HI! Thanks for you answers... (the link you gave me it is still not working). However, I do not have any answer for your questions, I can tell you that there are a lot of people working on PC, you can divide it in three groups: Curious, Interested in deep perfect single gadget (like you) and people interested in big tools, sometimes composed with libs and gadgets. So your destiny is  work on your child (Idea), make it perfect, every time and better than the previous version, unfortunately your big pleasure is that the third type of people apreciate your childs... that is.... In any case I have seen a lot of colorPker code on the net, and, in my opinion, your CP is the best I have found in the net. Unfortunately, for my needs, at the moment it is only a nice toy. For this reason I decided for another solution: I will do my own color piker.
Thanks a lot.

Cheers
Gildo

P.S. I will follow you because I am really interested in your future jobs.

**Comment by PitPik** [comment]
Hi @GildoMat ,
The link is http://github.com/PitPik/colorPicker/ ... for some reason this comment was rewriting the link. Maybe just copy and paste it.
Thanks for your answer and good luck with your new project!!
Cheers

**Pull request closed without merging**
